### ISSUE TITLE
Sorting and Color-coding

### ISSUE THREAD

**Issue by StefanBUE** [todotxt/todotxt#9]
Awesome tool, but color-coding the projects and categories would be even cooler.
And sorting is a must ;-)
Thx a lot, if you’d manage to add that Stefan

**Comment by karbassi** [comment]
@StefanBUE do you mean this for the [todo.txt-cli](https://github.com/todotxt/todo.txt-cli) project?

**Comment by StefanBUE** [comment]
Hi @karbassi , i was forwarded to this page from within the ios app Todotxt, so i thought that page belongs to it. But it looks like i m wrong. Sorry. You may close the suggestion.

**Comment by karbassi** [comment]
@StefanBUE Can you share what link you clicked on so we can update it?

**Comment by StefanBUE** [comment]
- start todotxt ios app
- click on filter icon in top right corner
- click on ? question mark symbol top right corner - that links you to here

**Comment by karbassi** [comment]
This issue was moved to todotxt/todo.txt-ios#254
